/**
 * Mapa central de íconos PielCalma — Phosphor.
 * Importado desde la entrada SSR para que sea seguro en Server Components
 * (sin IconContext). Pasar `weight` y `size` explícitos en cada uso.
 *
 * Convención: weight="duotone" para íconos-feature destacados,
 * weight="regular" o "bold" para UI/inline.
 */
export {
  Leaf,
  Wind,
  Sun,
  Moon,
  MoonStars,
  Waves,
  Question,
  HandHeart,
  Heart,
  HeartHalf,
  NotePencil,
  PencilSimpleLine,
  Camera,
  ImageSquare,
  UploadSimple,
  Eye,
  ArrowsLeftRight,
  Stethoscope,
  ShieldCheck,
  Info,
  Warning,
  Check,
  CheckCircle,
  ArrowRight,
  ArrowUpRight,
  ArrowLeft,
  Sparkle,
  ChartLineUp,
  FileText,
  FilePdf,
  Printer,
  ListChecks,
  ClipboardText,
  CalendarBlank,
  MapPin,
  ThermometerSimple,
  ChatCircleDots,
  Path,
  Quotes,
  BatteryLow,
  HandTap,
  ArrowClockwise,
  Plus,
  FloppyDisk,
  CaretDown,
  UsersThree,
  UserPlus,
  X,
} from "@phosphor-icons/react/dist/ssr";
